Added workflow to run pytest automatically
KitwareMedical/dicom-anonymizer pull request #52
Opened 2023-09-08 09:30 UTC by MntiKor

2023-09-08 09:37 UTC, finetjul commented
Please squash all your commits

2023-09-11 15:03 UTC, pchoisel commented
@MntiKor Please squash all your commits

2023-09-11 15:19 UTC, MntiKor commented
> @MntiKor Please squash all your commits

Done.

2023-09-11 15:44 UTC, pchoisel requested changes

2023-09-11 15:44 UTC, pchoisel commented on .github/workflows/tester.yml
> +name: unit-tests
Could you add caching on the `env` folder so we don't need to recreated the environment and install pytest each time we run the tests ?

2023-09-12 08:45 UTC, MntiKor commented on .github/workflows/tester.yml
> +      - run: env/bin/pytest
It appears I do need env/bin/, it doesnt work without

2023-09-12 09:23 UTC, pchoisel commented
LGTM
Thanks !

2023-09-12 09:23 UTC, merged